language: swift
os: osx
osx_image: xcode8.3
xcode_project: KikBot.xcodeproj
xcode_scheme: KikBot
install:
  - swift package fetch
script:
  - swift test
# - xcodebuild -project KikBot.xcodeproj -list
# - xcodebuild -scheme KituraNet -project KikBot.xcodeproj build
# - xcodebuild -scheme KikBot -project KikBot.xcodeproj test
after_success:
  - bash <(curl -s https://codecov.io/bash)
