language: swift
os: osx
osx_image: xcode8.3
xcode_project: KikBot.xcodeproj
xcode_scheme: KikBot
before_install:
  - brew update
script:
# - swift test
  - xcodebuild -scheme KikBot -project KikBot.xcodeproj -sdk iphonesimulator -destination 'platform=macOS, arch:x86_64' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
